### ISSUE TITLE
Opening Reading List sidebar causes DNS requests for every item saved

### ISSUE THREAD

**Issue by ghost** [WaldiPL/readingList#14]
Hi, thanks for this great addon.

I noticed that simply opening Reading List sidebar causes DNS requests for every item saved. I checked it in Wireshark. That's not desirable as it involves unnecessary bandwidth usage and privacy issues.  I would except such requests only for item that I interact with.

Opening firefox bookmark sidebar doesn't cause any DNS requests so it's addon specific issue.

I tested this on firefox 56

Is this behavior fixable?

**Comment by WaldiPL** [comment]
The cause of this problem is favicon downloading. In Firefox there is no suitable API to display favicons. Currently used is a direct link, (eg https://bugzilla.mozilla.org/extensions/BMO/web/images/favicon.ico) the size of these icons is small 1-10kB. Similar requests are sent when you open a new tab (Activity Stream) so I think this is not too much impact on privacy.

I will check whether it is possible to save favicons in Base64 format, and how this would affect performance.

**Comment by ghost** [comment]
Thanks for the answer!

I hope favicons can be saved same as they saved for firefox bookmarks. I don't have Activity Stream enabled so I don't know what it does. In my case for heavy Reading List usage we're talking about hundreds of domains...

**Comment by WaldiPL** [comment]
In version 1.4.5, favicons are saved in base64 format in the database.

**Comment by ghost** [comment]
Perfect! Thank you.
