### ISSUE TITLE
Open with reader mode

### ISSUE THREAD

**Issue by nt1m** [WaldiPL/readingList#15]
You can use:

```js
browser.tabs.create({
  url: ...,
  openInReaderMode: true
});
```

from Firefox 58 onwards

**Comment by nt1m** [comment]
There's also:
```js
tab.isInReaderMode // shows if the tab is in reader mode
tab.isArticle // shows if tab can be opened in reader mode
```

**Comment by WaldiPL** [comment]
Looks interesting, but I have some problems.

Pages are opened using the `<a href="">` so that you can open it in the background.
Click event works only for LMB. Mouseup event also causes problems, such as when you click MMB, the autoscroll icon appears.

I tried using `tabs.toggleReaderMode()`, works fine, but can not turn off reader mode, because it turns on automatically.

If I find a good solution then I will add this function.

**Comment by owensgithub** [comment]
Hi. There's a new API for reader mode. See here for more details https://blog.mozilla.org/addons/2017/11/20/extensions-in-firefox-58/

**Comment by WaldiPL** [comment]
Please test this feature in the latest version. This is disabled by default because it does not work like I would like (current API is insufficient).

**Comment by owensgithub** [comment]
Hi. I think it’s great so far. I’m not sure if the 4 options are necessary though. Maybe, keep it simple and have:

Reader View Off
Reader View On
Reader View On (force all)

Seems to be an issue when I choose ‘Open only those pages that certainly can be displayed’. I need to click it twice to open Reader View. It’s working fine when I choose ‘Open pages except those that certainly can not be displayed’. Could maybe keep the latter option as it’s working fine, and remove the former option as you need to double click it for it to work.

Overall, very useful feature.

**Comment by WaldiPL** [comment]
The difference between ‘Open only those pages that certainly can be displayed’ and ‘Open pages except those that certainly can not be displayed’ will be visible only to current users who have added pages to the list. If you select 'Open pages except those that certainly can not be displayed', all old pages will be opened in reader mode. (Also those that can not be displayed properly.)

> Seems to be an issue when I choose ‘Open only those pages that certainly can be displayed’. I need to click it twice to open Reader View.

This is due to the lack of information whether the page can be properly displayed in reader mode.
